# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- dev
- feature/*

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'a4cfea1d-a32a-4f5c-bef1-8fed3c3f0294'
  imageRepository: 'asevilla'
  containerRegistry: 'itvitaecontainerregistry.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'itvitaecontainerregistry90af-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Environment Deployment depends on branch
  ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}: 
    environmentDeployment: 'asevilla.asevilla-dev'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}: 
    environmentDeployment: 'asevilla.asevilla-prod'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:  
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Test
  displayName: Docker test
  dependsOn: Build
  jobs:  
  - job: Test
    displayName: Test
    pool:
      vmImage: $(vmImageName)
    container:
      image: $(containerRegistry)/$(imageRepository):$(tag)
      endpoint: 'itvitaecontainerregistry'
    steps:
    - script: |
        pytest --junitxml=junit/test-results.xml --cov=. --cov-report=xml

    - script: |
        flake8 app tests

    - script: |
        isort -v app tests

    - script: |
        black -v app tests

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'junit/test-*.xml'
        searchFolder: '$(Build.SourcesDirectory)'
    
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.xml'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Test
  condition: and(succeeded(), ne(variables['environmentDeployment'], ''))

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: $(environmentDeployment)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
