apiVersion: v1
kind: Service
metadata:
  name: demok8s-3
  namespace: exercise1
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    k8s-app: demok8s-3